// Sample menu items for demonstration
export const sampleMenuItems = [
    {
      id: 1,
      name: "Margherita Pizza",
      description: "Classic pizza with tomato sauce, mozzarella, and basil",
      price: 12.99,
      category: "pizza",
      image: "/placeholder.svg?height=150&width=200&text=Pizza",
    },
    {
      id: 2,
      name: "Pepperoni Pizza",
      description: "Pizza topped with pepperoni slices and cheese",
      price: 14.99,
      category: "pizza",
      image: "/placeholder.svg?height=150&width=200&text=Pepperoni",
    },
    {
      id: 3,
      name: "Classic Burger",
      description: "Beef patty with lettuce, tomato, and special sauce",
      price: 9.99,
      category: "burgers",
      image: "/placeholder.svg?height=150&width=200&text=Burger",
    },
    {
      id: 4,
      name: "Cheeseburger",
      description: "Classic burger with American cheese",
      price: 10.99,
      category: "burgers",
      image: "/placeholder.svg?height=150&width=200&text=Cheeseburger",
    },
    {
      id: 5,
      name: "California Roll",
      description: "Crab, avocado, and cucumber roll",
      price: 16.99,
      category: "sushi",
      image: "/placeholder.svg?height=150&width=200&text=Sushi",
    },
    {
      id: 6,
      name: "Pasta Carbonara",
      description: "Creamy pasta with bacon and parmesan",
      price: 14.99,
      category: "pasta",
      image: "/placeholder.svg?height=150&width=200&text=Pasta",
    },
    {
      id: 7,
      name: "Chocolate Cake",
      description: "Rich chocolate cake with ganache",
      price: 7.99,
      category: "desserts",
      image: "/placeholder.svg?height=150&width=200&text=Cake",
    },
    {
      id: 8,
      name: "Iced Coffee",
      description: "Cold brewed coffee with milk",
      price: 4.99,
      category: "drinks",
      image: "/placeholder.svg?height=150&width=200&text=Coffee",
    },
  ]
  
  // Sample orders for demonstration
  export const sampleOrders = [
    {
      id: "3210",
      customer: {
        name: "Olivia Martin",
        email: "olivia@example.com",
        phone: "(123) 456-7890",
        address: "123 Main St",
        city: "New York",
        zipCode: "10001",
      },
      items: [
        { id: 1, name: "Margherita Pizza", price: 12.99, quantity: 2 },
        { id: 7, name: "Chocolate Cake", price: 7.99, quantity: 1 },
      ],
      total: 42.25,
      date: "2023-04-04T14:30:00Z",
      status: "Delivered",
      paymentMethod: "credit",
    },
    {
      id: "3209",
      customer: {
        name: "Ava Johnson",
        email: "ava@example.com",
        phone: "(234) 567-8901",
        address: "456 Oak St",
        city: "Los Angeles",
        zipCode: "90001",
      },
      items: [
        { id: 3, name: "Classic Burger", price: 9.99, quantity: 3 },
        { id: 8, name: "Iced Coffee", price: 4.99, quantity: 3 },
      ],
      total: 74.99,
      date: "2023-04-03T12:15:00Z",
      status: "Processing",
      paymentMethod: "credit",
    },
    {
      id: "3208",
      customer: {
        name: "Michael Brown",
        email: "michael@example.com",
        phone: "(345) 678-9012",
        address: "789 Pine St",
        city: "Chicago",
        zipCode: "60007",
      },
      items: [
        { id: 5, name: "California Roll", price: 16.99, quantity: 1 },
        { id: 8, name: "Iced Coffee", price: 4.99, quantity: 1 },
      ],
      total: 32.5,
      date: "2023-04-02T18:45:00Z",
      status: "Pending",
      paymentMethod: "cash",
    },
    {
      id: "3207",
      customer: {
        name: "Sophia Anderson",
        email: "sophia@example.com",
        phone: "(456) 789-0123",
        address: "101 Maple St",
        city: "Houston",
        zipCode: "77001",
      },
      items: [
        { id: 2, name: "Pepperoni Pizza", price: 14.99, quantity: 2 },
        { id: 4, name: "Cheeseburger", price: 10.99, quantity: 3 },
        { id: 7, name: "Chocolate Cake", price: 7.99, quantity: 2 },
      ],
      total: 99.99,
      date: "2023-04-01T20:30:00Z",
      status: "Delivered",
      paymentMethod: "credit",
    },
    {
      id: "3206",
      customer: {
        name: "Daniel Smith",
        email: "daniel@example.com",
        phone: "(567) 890-1234",
        address: "202 Elm St",
        city: "Phoenix",
        zipCode: "85001",
      },
      items: [
        { id: 6, name: "Pasta Carbonara", price: 14.99, quantity: 3 },
        { id: 8, name: "Iced Coffee", price: 4.99, quantity: 2 },
      ],
      total: 67.5,
      date: "2023-03-31T19:15:00Z",
      status: "Cancelled",
      paymentMethod: "credit",
    },
  ]
  
  